# Generated by Django 5.1.4 on 2025-01-10 03:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outliner', '0002_plot_archetype_causeofdeath_character_motives_role_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aplot',
            name='archetype',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='outliner.archetype'),
        ),
        migrations.AddField(
            model_name='aplot',
            name='cause_of_death',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='outliner.causeofdeath'),
        ),
        migrations.AddField(
            model_name='aplot',
            name='murder',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='aplot',
            name='red_herrings',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='bplot',
            name='connection_to_a_plot',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='character',
            name='alibi',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='character',
            name='background',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='character',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='character',
            name='motive',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='character',
            name='role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='outliner.role'),
        ),
        migrations.AddField(
            model_name='character',
            name='secrets',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='cplot',
            name='connection_to_a_plot',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='cplot',
            name='connection_to_b_plot',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='plot',
            name='characters',
            field=models.ManyToManyField(blank=True, to='outliner.character'),
        ),
        migrations.AddField(
            model_name='project',
            name='chapters',
            field=models.ManyToManyField(blank=True, to='outliner.chapter'),
        ),
        migrations.AddField(
            model_name='project',
            name='characters',
            field=models.ManyToManyField(blank=True, to='outliner.character'),
        ),
        migrations.AddField(
            model_name='project',
            name='plot_a',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='a_plots', to='outliner.aplot'),
        ),
        migrations.AddField(
            model_name='project',
            name='plot_b',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='b_plots', to='outliner.bplot'),
        ),
        migrations.AddField(
            model_name='project',
            name='plot_c',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='c_plots', to='outliner.cplot'),
        ),
        migrations.AlterField(
            model_name='archetype',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='archetype',
            name='examples',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='causeofdeath',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='motives',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='plot',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='role',
            name='description',
            field=models.TextField(default=''),
        ),
    ]
